### ISSUE TITLE
无法启动项目

### ISSUE THREAD

**Issue by hyp530** [zerlei/me#1]
```
npm intall
npm run docs:dev
```

**Comment by zerlei** [comment]
我在 codespaces 看了一下，是版本兼容的问题。

您按照下面改一下看看是不是可以？
![image](https://github.com/ZhaoYouYa/me/assets/40014687/286ec386-9d97-44ed-a892-fe9426fb8818)

codespaces npm 的版本
```bash
npm -v
# 10.2.4
```

我平常用的是 [bun](https://bun.sh/)♥️，同时，我这个是自用啊，大哥😅

**Comment by zerlei** [comment]
推荐您可以看看下面的 vitepress  blog 主题：
https://github.com/ATQQ/sugar-blog?tab=readme-ov-file

https://github.com/clark-cui/vitepress-blog-zaun
